"""
File: llm.py

Purpose:
This module uses an Ollama Large Language Model (LLM) to convert
a natural language question into a valid DuckDB SQL query.

Workflow:
1. Accepts the user's question and database schema.
2. Creates a detailed prompt for the LLM.
3. Sends the prompt to Ollama.
4. Receives the generated SQL query.
5. Cleans the response by removing Markdown formatting.
6. Extracts and returns only the SQL query.
"""

import ollama
import re

# Name of the Ollama model used for SQL generation
MODEL_NAME = "deepseek-coder:6.7b"
# MODEL_NAME = "llama3.2"


def generate_sql(question, schema):
    """
    Generates a DuckDB SQL query from a natural language question.

    Parameters:
        question (str): User's natural language question.
        schema (str): Database schema containing tables and columns.

    Returns:
        str: A valid DuckDB SQL query generated by the LLM.
    """

    # Prompt sent to the LLM
    prompt = f"""
You are an expert Text-to-SQL assistant specialized in DuckDB.

Your task is to generate exactly ONE valid DuckDB SQL query.

Database Schema:
{schema}

Instructions:
1. Generate the SQL query that answers the question.
2. Use ONLY the tables listed in the schema.
3. Use ONLY the columns listed in the schema.
4. Never invent table names.
5. Never invent column names.
6. Never invent values.
7. Return ONLY the SQL query.
8. Do NOT explain anything.
9. End the SQL query with a semicolon.

Question:
{question}

SQL:
"""

    # Send the prompt to the Ollama model
    response = ollama.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    # Extract the generated response
    sql = response["message"]["content"].strip()

    # Remove Markdown formatting if present
    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")
    sql = sql.strip()

    # Extract only the SQL query from the response
    match = re.search(
        r"(SELECT|WITH).*?;",
        sql,
        flags=re.IGNORECASE | re.DOTALL
    )

    # Return the extracted SQL query if found
    if match:
        return match.group(0).strip()

    # Return the original response if no SQL pattern is found
    return sql