"""
File: llm_wikisql.py

Purpose:
This module generates DuckDB SQL queries for the WikiSQL evaluation
dataset using an Ollama Large Language Model (LLM).

Unlike the main application, this module receives the table name
and schema for each WikiSQL test case and generates a SQL query
based on the provided natural language question.

Workflow:
1. Accept the question, table name, and schema.
2. Create a prompt for the LLM.
3. Send the prompt to Ollama.
4. Receive the generated SQL query.
5. Remove any Markdown formatting.
6. Extract and return only the SQL query.
"""

import ollama
import re

# Name of the Ollama model used for SQL generation
MODEL_NAME = "deepseek-coder:6.7b"
# MODEL_NAME = "llama3.2"


def generate_sql(question, table_name, schema):
    """
    Generates a DuckDB SQL query for a WikiSQL question.

    Parameters:
        question (str): Natural language question from the WikiSQL dataset.
        table_name (str): Name of the table associated with the question.
        schema (str): Schema of the corresponding table.

    Returns:
        str: A valid DuckDB SQL query generated by the LLM.
    """

    # Prompt provided to the LLM
    prompt = f"""
You are an expert Text-to-SQL assistant specialized in DuckDB.

Your task is to generate exactly ONE valid DuckDB SQL query that answers the user's natural language question.

Table Name:
{table_name}

Schema:
{schema}

Instructions:
1. Generate the SQL query that answers the given question.
2. Use ONLY the table "{table_name}".
3. Use ONLY the columns listed in the schema.
4. Never invent table names.
5. Never invent column names.
6. Never invent values.
7. Preserve values exactly as they appear in the question whenever possible.
8. Use single quotes (' ') for all string literals.
9. Return ONLY the SQL query.
10. Do NOT explain anything.
11. Do NOT use Markdown.
12. End the SQL query with a semicolon.

Question:
{question}

SQL:
"""

    # Send the prompt to the Ollama model
    response = ollama.chat(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    # Extract the generated response
    sql = response["message"]["content"].strip()

    # Remove Markdown formatting if present
    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")
    sql = sql.strip()

    # Extract only the SQL query
    match = re.search(
        r"(SELECT|WITH).*?;",
        sql,
        flags=re.IGNORECASE | re.DOTALL
    )

    # Return the extracted SQL query if found
    if match:
        return match.group(0).strip()

    # Return the original response if no SQL query is detected
    return sql