"""
File: mcp_client.py

Purpose:
This module provides an interface for executing SQL queries
through the DuckDB MCP (Model Context Protocol) server.

Workflow:
1. Starts the DuckDB MCP server.
2. Establishes a connection using the MCP client.
3. Sends the SQL query to the MCP server.
4. Receives the query result.
5. Returns the result to the application.
"""

import asyncio
import ast

from mcp.client.session import ClientSession
from mcp.client.stdio import stdio_client, StdioServerParameters


class MCPClient:
    """
    Handles communication with the DuckDB MCP server.
    """

    def __init__(self):
        """
        Configures the MCP server connection.
        """

        # Configure the DuckDB MCP server
        self.server = StdioServerParameters(
            command="python",
            args=[
                "-m",
                "uv",
                "tool",
                "run",
                "mcp-server-duckdb",
                "--db-path",
                "data/company.duckdb"
            ]
        )

    async def execute(self, sql):
        """
        Executes a SQL query through the MCP server.

        Parameters:
            sql (str): SQL query generated by the LLM.

        Returns:
            list | str:
                Query result returned by the MCP server.
        """

        # Start communication with the MCP server
        async with stdio_client(self.server) as (read, write):

            # Create a client session
            async with ClientSession(read, write) as session:

                # Initialize the MCP session
                await session.initialize()

                # Send the SQL query to the MCP server
                result = await session.call_tool(
                    "query",
                    {
                        "query": sql
                    }
                )

                # Extract the response
                text = result.content[0].text

                # Convert the response into a Python object if possible
                try:
                    return ast.literal_eval(text)

                # Return the original text if conversion fails
                except:
                    return text


# Create a reusable MCP client instance
_client = MCPClient()


def execute_sql(sql):
    """
    Executes a SQL query synchronously through the MCP client.

    Parameters:
        sql (str): SQL query to execute.

    Returns:
        list | str:
            Query result returned by the MCP server.
    """

    return asyncio.run(
        _client.execute(sql)
    )