"""
File: validator.py

Purpose:
This module validates SQL queries before execution.

It uses DuckDB's EXPLAIN statement to check whether the
generated SQL query is syntactically correct and references
valid tables and columns.

If the SQL query is invalid, the corresponding error message
is displayed to help with debugging.
"""

import duckdb

# Path to the DuckDB database
DB_PATH = "data/company.duckdb"


def validate_sql(sql):
    """
    Validates a generated SQL query.

    Parameters:
        sql (str): SQL query generated by the LLM.

    Returns:
        bool:
            True if the SQL query is valid.
            False if the query contains syntax or schema errors.
    """

    # Connect to the DuckDB database
    conn = duckdb.connect(DB_PATH)

    try:

        # Use EXPLAIN to validate the SQL query without executing it
        conn.execute("EXPLAIN " + sql)

        # Close the database connection
        conn.close()

        return True

    except Exception as e:

        # Close the database connection if validation fails
        conn.close()

        print("\nValidation Error:")
        print(e)

        return False